/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.oasis.okt.orm


class StringUtils {
    companion object {
        fun join(source: List<String>): String {
            return source.joinToString(",")
        }

        fun split(source: String): List<String> {
            return source.split(',')
        }
    }
}
