/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("okt-web-common-conventions")
}
dependencies {
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-auth:$ktorVersion")
    implementation("io.ktor:ktor-serialization:$ktorVersion")

    // ktor-client
    implementation("io.ktor:ktor-client-core:$ktorVersion")
    implementation("io.ktor:ktor-client-apache:$ktorVersion")
    implementation("io.ktor:ktor-client-core-jvm:$ktorVersion")
    implementation("io.ktor:ktor-client-cio:$ktorVersion")
    implementation("io.ktor:ktor-client-gson:$ktorVersion")

    // swagger support
    implementation("org.webjars:swagger-ui:$swaggerUiVersion")
    implementation("io.swagger.core.v3:swagger-core:$swaggerCoreVersion")
    implementation("io.swagger.core.v3:swagger-models:$swaggerCoreVersion")

    // freemarker
    implementation("io.ktor:ktor-html-builder:$ktorVersion")
    implementation("io.ktor:ktor-freemarker:$ktorVersion")
    implementation("io.ktor:ktor-webjars:$ktorVersion")

    //validate
    implementation("org.hibernate.validator:hibernate-validator:$hibernateValidatorVersion") {
        exclude(group = "jakarta.validation", module = "jakarta.validation-api")
    }
    implementation("jakarta.validation:jakarta.validation-api:$jakartaValidationApiVersion")
    implementation("org.glassfish:jakarta.el:$jakartaElVersion")
}