/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("okt-web-common-conventions")
}
dependencies {
    api("io.ktor:ktor-server-netty:$ktorVersion")
    api("io.ktor:ktor-server-core:$ktorVersion")
    api("io.ktor:ktor-auth:$ktorVersion")
    api("io.ktor:ktor-auth-jwt:$ktorVersion")
    api("io.ktor:ktor-server-sessions:$ktorVersion")
    api("io.ktor:ktor-serialization:$ktorVersion")

    // ktor-client
    api("io.ktor:ktor-client-core:$ktorVersion")
    api("io.ktor:ktor-client-apache:$ktorVersion")
    api("io.ktor:ktor-client-core-jvm:$ktorVersion")
    api("io.ktor:ktor-client-cio:$ktorVersion")
    api("io.ktor:ktor-client-gson:$ktorVersion")

    // swagger support
    implementation("org.webjars:swagger-ui:$swaggerUiVersion")
    implementation("io.swagger.core.v3:swagger-core:$swaggerCoreVersion"){
        exclude(group = "jakarta.validation")
        exclude(group = "jakarta.xml.bind")
    }
    implementation("io.swagger.core.v3:swagger-models:$swaggerCoreVersion")

    // freemarker
    api("io.ktor:ktor-html-builder:$ktorVersion")
    api("io.ktor:ktor-freemarker:$ktorVersion")
    api("io.ktor:ktor-webjars:$ktorVersion")

    //log
    implementation("ch.qos.logback:logback-classic:$logbackVersion")

    //validate
    api("org.hibernate.validator:hibernate-validator:$hibernateValidatorVersion")
    api("jakarta.validation:jakarta.validation-api:$jakartaValidationApiVersion")
    api("org.glassfish:jakarta.el:$jakartaElVersion")
}