/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("okt-web-common-conventions")
}
dependencies {
    // mysql
    api("mysql:mysql-connector-java:$mysqlVersion")

    // hikari
    api("com.zaxxer:HikariCP:$hikariVersion")

    // exposed
    api("org.jetbrains.exposed:exposed-core:$exposedVersion")
    api("org.jetbrains.exposed:exposed-dao:$exposedVersion")
    api("org.jetbrains.exposed:exposed-jdbc:$exposedVersion")

    //reflections
    implementation("org.reflections:reflections:$reflectionsVersion")
    //JColor
    implementation("com.diogonunes:JColor:$jColorVersion")
}